name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # Mantemos versões estáveis e LTS para garantir compatibilidade e suporte contínuo

    steps:
      # Verifica o código na branch
      - uses: actions/checkout@v4

      # Configura a versão do Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  # Cache de dependências para acelerar o workflow [[3]](https://poe.com/citation?message_id=258600571039&citation=3)

      # Instalação de dependências
      - name: Install dependencies
        run: npm ci

      # Realiza a build do projeto
      - name: Build the project
        run: npm run build --if-present

      # Roda os testes
      - name: Run Tests
        run: npm test

      # Salvando qualquer artefato relevante, como logs ou resultados de testes
      - name: Save test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results/  # Certifique-se de que esta pasta existe no projeto [[3]](https://poe.com/citation?message_id=258600571039&citation=3)

      # Opcional: Verificação adicional se houver contratos inteligentes a serem compilados
      - name: Compile Smart Contracts
        run: npm run compile --if-present
